[tool.poetry]
name = "scrapysplashwrapper"
version = "1.0"
description = "Scrapy splash wrapper as a standalone library."
authors = ["Raphaël Vinot <raphael.vinot@circl.lu>"]
license = "BSD-3-Clause"
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.6"
scrapy = "^1.8.0"
scrapy-splash = "^0.7.2"

[tool.poetry.dev-dependencies]
mypy = "^0.761"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
